### ISSUE TITLE
misnaming of binary qps

### ISSUE THREAD

**Issue by pmattern** [QtDesktop/qps#11]
Due to a regression in 56d9096 the actual binary gets named `Project` instead of `qps`.

E. g. running
```
cmake <path to sources> -DCMAKE_INSTALL_PREFIX=/usr
make
make install
```
from a suitable `build` dir yields `/usr/bin/Project` instead of `/usr/bin/qps`.

**Comment by luis-pereira** [comment]
@pmattern Don't know how, but just committed one part of the patch.
