### ISSUE TITLE
Crash and core dump upon exit, apparently due to compiling against Qt 5.6

### ISSUE THREAD

**Issue by pmattern** [QtDesktop/qps#13]
Commit 3e80692 is reproducibly crashing and dumping core upon exit on recent Arch Linux.

Problem seems to be related to Qt 5.*6* as it got manifest only after compiling the said commit against Qt 5.6 but wasn't when the the same commit was compiled against Qt 5.5 for about a month.

Stack trace / backtrace on https://gist.github.com/pmattern/ccd321bc00789b5e4bdd43c885ac1530.

**Comment by ozky** [comment]
It's not in qt i have no any crash in Mageia Cauldron qt 5.6 with qps....
I also compiled it against Mageia 5 qt community binary installed qt5.6 no any crash.

**Comment by agaida** [comment]
@ozky - and that prove exactly what? - ok, you compile it and it don't crash, some other people compile it and have crashes. So it might be that there are different build options, triggers and switches are set. And it might be that Qt is build with other activated options and so on. And it would be fine if we could track this down, Works for me (us)™ doesn't really help.

**Comment by jleclanche** [comment]
Actually this is a WFM scenario. It was probably crashing due to a missing qtplugin rebuild.

**Comment by pmattern** [comment]
Having another look at 7e679db clearly demonstrates the problem persists but seems to take place in LXQt sessions only.

Running this commit in LXQt sessions triggers 100% reproducibly a crash upon exiting the application here. Same findings running LXQt Git checkouts on Arch Linux "bare metal" and in QEMU virtual machines and on Debian testing running LXQt 0.10 from the official repositories in QEMU virtual machines. Traces still the same as linked in the initial comment above, even when CMAKE_BUILD_TYPE is set to Debug instead of Release.
The crashes can not be seen in KDE, Xfce or Openbox ("only" / no desktop environment) sessions, though.

@jleclanche
Did you test on Arch Linux before calling this WFM and closing the issue?

This whole thing makes me wonder whether there's a bug in LXQt triggering crashes upon exit. See e. g. lxde/lxqt#1084 as well.

**Comment by jleclanche** [comment]
Yes I did test it on arch.
