### ISSUE TITLE
Make a release so distro can pack

### ISSUE THREAD

**Issue by Arnaudv6** [QtDesktop/qps#14]
Hello, please make a release, so distros can pack qps with a version number.

**Comment by ozky** [comment]
Plus million many distro have not packaged qps because it's git only and distros avoid alpha/git softwares in stable releases.

**Comment by jleclanche** [comment]
qps is not really maintained. The codebase needs a complete overhaul and cleanup - as long as that doesn't happen, a release is kind of pointless.

**Comment by ozky** [comment]
Yes you are right but why fork it and then stop development it ? same with easypaint.

**Comment by jleclanche** [comment]
At the time of the fork, we had people willing to work on it. Right now, nobody is stepping up.

**Comment by agaida** [comment]
some whishes last a little bit longer - done

**Comment by Arnaudv6** [comment]
...and they bring the more joy.
Thanks, Alf: this is great.
