### ISSUE TITLE
Summary - not really a bug

### ISSUE THREAD

**Issue by agaida** [QtDesktop/qps#33]
I have changed some things in the last week that was long overdue:
* Licenses and license headers
* Removed any not UTF 8 encoding from any file - so we can open the project in KDevelop or the Qt IDE again without hangs or crashes
* Removed some empty and not used files
* Removed a generated not used ressource file

TODO
* Remove some dead code
* Some kind of code cleanup - code style, trailing whitespaces and so on

That will not change nothing in the functionality nor solve any bugs but might make the code more maintainable.

**Comment by agaida** [comment]
@tsujan - what do you think?

**Comment by tsujan** [comment]
I agree and add this:

● Code comments seem to be very personal. They should be made clear to all.

I'll fix comments while I'll fix the code (already done in some places).

**Comment by agaida** [comment]
Come on - the code base is older than few of our users - so code and comment style change over time. :)

**Comment by tsujan** [comment]
@agaida I ask out of curiosity: do you know the name of the original author? I couldn't find a name, as if the app was written by itself ;)

**Comment by tsujan** [comment]
And if it's so old, we should really think about restructuring it (those custom widgets I mentioned elsewhere).

**Comment by agaida** [comment]
of course we should 
```
 * commanddialog.h
 * This file is part of qps -- Qt-based visual process status monitor
 *
 * Copyright 1997-1999 Mattias Engdegård
 *
```

**Comment by tsujan** [comment]
Wow! Now I understand why the code looked so weird to me! It'll be a lot of work. I give priority to LXQt and my projects.

I know that it has been modified but still it's amazing that it works -- maybe because of Qt's power.

**Comment by agaida** [comment]
my plan was and is - clean some things up without breaking anything and pave the way for some improvements. We shouldn't break things if we are not forced to do so in that project. I think the principles of chess apply here: 1. Carefully 2. Carefully 3. Carefully

**Comment by tsujan** [comment]
If by breaking you mean damaging, it souldn't be done anywhere. But if you mean breaking the current code structure, it *should* be done in this case.

What I mean is *improving* the app by changing its code structure to make the current features better and then, probably, add more features.

**Comment by agaida** [comment]
what i mean was - clean up if possible first - dead code and such things - and we should release it before we break it :D

**Comment by tsujan** [comment]
Oh, I agree, of course.

I was just thinking about future -- there were vague images in my mind about which widget should be replaced by which. However, frankly speaking, it isn't what I could do because when I start to work on the code, I can't help changing its structure ;)

**Comment by agaida** [comment]
no problem

**Comment by agaida** [comment]
@tsujan - .17 is out, you can sharpen and use your chainsaw :D

**Comment by tsujan** [comment]
:)

If LXQt and my own projects don't take all of my free time... I can imagine a lot of things to fix or add just in the case of pcmanfm-qt ;)
