### ISSUE TITLE
add desktop entry file

### ISSUE THREAD

**Issue by pmattern** [QtDesktop/qps#6]
Currently there's no desktop entry file.

Proposal regarding the file itself
```
[Desktop Entry]
Type=Application
Name=qps
GenericName=Qt process manager
Comment=Qt application to display and manage running processes
Icon=qps
Categories=System;
TryExec=qps
Exec=qps
Terminal=false
StartupNotify=false
```
Adding this file would obviously involve that an icon is added as well. In my opinion the most suitable choice would be to copy `icon/icon.xpm` to `/usr/share/icons/hicolor/48x48/apps/qps.xpm`.

XPM files aren't recommended any longer but still supported by the [Specification](http://standards.freedesktop.org/icon-theme-spec/latest/ar01s02.html). In the long rung substitution with a more suitable file type and / or even another icon as a whole is probably something worth considering.
Different story, of course.

**Comment by scootergrisen** [comment]
I suggest adding these strings to the .ts files so people can translate them from the ts files.
