### ISSUE TITLE
add internationalization / localization

### ISSUE THREAD

**Issue by pmattern** [QtDesktop/qps#7]
Title says it basically all, already: internationalization / localization would be something nice to have.

**Comment by pmattern** [comment]
While trying to translate into German I made some findings that I'd hereby like to discuss (line numbers referring to a version of qps.ts I pushed to https://github.com/pmattern/qps featuring some small changes to improve readability):

Running qps I failed to figure out which GUI elements the translations actually belong to.
Neither a control bar (context ControlBar), nor a dialog window "Watchdog 0.1 alpha" (EventDialog) or "Qps" (ExecWindow) seemed to exist. Also it wasn't clear to me which UI elements belong to the two remaining contexts "Qps" and "Screenshot".
So I wonder how all these elements can get displayed or whether they may eventually have been removed in the meantime.

Some things don't seem to be quite correct in individual contexts:
*EventDialog*
`<source>` and `</source>` aren't just enclosing the strings to get translated as usual but objects like QPushButtonX, QWidget or QFrame as can be seen in lines 22-43. Opening the file in QtLinguist doesn't make things more plausible either. So I wonder whether placing those objects like this was really intentional.
Shouldn't this be "labelDescri*p*tion" in line 58?
Cannot see any sense in strings `acdcd`, `ddddd`, `ccccc` and `aaaa` (lines 78, 83, 88, 93).
*ExecWindow*
The window title states "Qps" while the name is written lower case everywhere else. For sure not a bummer but I think it would be good to have the name written consistently everywhere - no matter how exactly it's written.
*Screenshot*
Wondering whether the initial slash in `/untitled` makes sense.

Several elements seem to be missing.
Namely all topics from the main menu and the context menu of single processes, including dialog windows which can be invoked from the respective menu, as well as "Process count" in status bar.

**Comment by agaida** [comment]
@luis-pereira: i reopend this at @pmattern s request - may be a separated issue will be better

**Comment by luis-pereira** [comment]
@agaida I will take a look. I applied the usual recipe.

**Comment by agaida** [comment]
@luis-pereira thank you very much

**Comment by luis-pereira** [comment]
@pmattern @agaida Just pushed `watchdog.ui` fixes and updated translations sources.
Other issues are pending. qps wasn't developed with internationalization in mind. There ate tons of missing `tr()` and in some cases translating it will break stuff. See [this](https://github.com/QtDesktop/qps/blob/master/src/qps.cpp#L969).

It will take some effort to make it right. I'm on a little break. I'm fixing this on a "summer mode".

**Comment by agaida** [comment]
@luis-pereira no problem, thank you for working on this
